name: Next.js CI/CD with Cypress and Caching

on: [push]

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Cache Next.js build files
        uses: actions/cache@v3
        with:
          path: .next
          key: nextjs-build-${{ runner.os }}-${{ hashFiles('**/.next/**') }}